# -*- coding: utf-8 -*-
"""
train_estimator.py - Train BehavioralSkillEstimator (LSTM).

Trains on synthetic session data generated by generate_synthetic_sessions.py.
Input: sliding window of 3 consecutive level-play observations (6 features each)
Output: scalar skill estimate in [0, 1]

After training, updates serve.py to use LSTM instead of simple heuristic.

Run: python flowlevel/src/skill/train_estimator.py
Output: models/skill_estimator.pt
"""

import os, sys
PROJECT_DIR = r"D:\College\Sem VI\Minor Project\flowlevel"
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

DATA_DIR  = os.path.join(PROJECT_DIR, "data")
MODEL_DIR = os.path.join(PROJECT_DIR, "models")

WINDOW_SIZE = 3       # number of consecutive levels to look back
N_FEATURES  = 6      # features per level: [solve_time, moves, solved, undos, time_var, skill_target]
HIDDEN_SIZE = 64
EPOCHS      = 100
LR          = 1e-3
BATCH_SIZE  = 64
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"


# ── Load data ─────────────────────────────────────────────────────────────────
print("Loading synthetic session data...")
features_raw = np.load(os.path.join(DATA_DIR, "synthetic_sessions.npy"))  # (N, 6)
labels_raw   = np.load(os.path.join(DATA_DIR, "synthetic_labels.npy"))    # (N,)
N_total = len(features_raw)
print(f"  {N_total} data points loaded.")

# Normalise features (except skill_target col which is already [0,1])
mean = features_raw[:, :5].mean(0)
std  = features_raw[:, :5].std(0) + 1e-8
features_norm = features_raw.copy()
features_norm[:, :5] = (features_raw[:, :5] - mean) / std
np.save(os.path.join(MODEL_DIR, "estimator_scaler.npy"), np.stack([mean, std]))

# Build sliding window sequences
# Each sample: (window_size, n_features) → label scalar
X_windows, y_labels = [], []
for i in range(WINDOW_SIZE - 1, N_total):
    window = features_norm[i - WINDOW_SIZE + 1 : i + 1]   # (window, 6)
    X_windows.append(window)
    y_labels.append(labels_raw[i])

X_tensor = torch.tensor(np.array(X_windows), dtype=torch.float32)  # (M, window, 6)
y_tensor = torch.tensor(np.array(y_labels),  dtype=torch.float32)  # (M,)

# Train/val split 80/20
n_train = int(0.8 * len(X_tensor))
X_train, X_val = X_tensor[:n_train], X_tensor[n_train:]
y_train, y_val = y_tensor[:n_train], y_tensor[n_train:]

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(TensorDataset(X_val,   y_val),   batch_size=BATCH_SIZE)
print(f"  Train: {n_train}  Val: {len(X_val)}  Windows shape: {X_tensor.shape}")


# ── Model ─────────────────────────────────────────────────────────────────────
class BehavioralSkillEstimator(nn.Module):
    """
    Maps a window of player behavior observations to a skill level estimate.
    Input:  (batch, window_size, n_features)
    Output: (batch,) scalar in [0, 1]
    """
    def __init__(self, n_features=N_FEATURES, window_size=WINDOW_SIZE, hidden=HIDDEN_SIZE):
        super().__init__()
        self.lstm = nn.LSTM(n_features, hidden, batch_first=True, num_layers=2, dropout=0.2)
        self.head = nn.Sequential(
            nn.Linear(hidden, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 1),
            nn.Sigmoid(),
        )

    def forward(self, x):
        # x: (batch, window, features)
        _, (h, _) = self.lstm(x)
        return self.head(h[-1]).squeeze(-1)   # use last layer hidden state


# ── Training ──────────────────────────────────────────────────────────────────
model   = BehavioralSkillEstimator().to(DEVICE)
opt     = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)
loss_fn = nn.MSELoss()
scheduler = torch.optim.lr_scheduler.StepLR(opt, step_size=30, gamma=0.5)

print(f"\nParameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Training {EPOCHS} epochs on {DEVICE}...\n")

best_val_loss = float("inf")
best_state    = None

for epoch in tqdm(range(EPOCHS), desc="LSTM Estimator"):
    # --- Train ---
    model.train()
    train_loss = 0.0
    for xb, yb in train_loader:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        pred   = model(xb)
        loss   = loss_fn(pred, yb)
        opt.zero_grad(); loss.backward(); opt.step()
        train_loss += loss.item()

    # --- Validate ---
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            val_loss += loss_fn(model(xb), yb).item()

    train_loss /= len(train_loader)
    val_loss   /= len(val_loader)
    scheduler.step()

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_state    = {k: v.clone() for k, v in model.state_dict().items()}

    if (epoch + 1) % 20 == 0:
        tqdm.write(f"  Epoch {epoch+1:3d}  train={train_loss:.5f}  val={val_loss:.5f}")


# ── Save ──────────────────────────────────────────────────────────────────────
model.load_state_dict(best_state)
save_path = os.path.join(MODEL_DIR, "skill_estimator.pt")
torch.save({
    "model_state":   best_state,
    "config": {
        "n_features":  N_FEATURES,
        "window_size": WINDOW_SIZE,
        "hidden_size": HIDDEN_SIZE,
    },
    "scaler_mean": mean.tolist(),
    "scaler_std":  std.tolist(),
    "best_val_mse": best_val_loss,
}, save_path)
print(f"\nSkill estimator saved: {save_path}")
print(f"Best val MSE: {best_val_loss:.5f}  (RMSE = {best_val_loss**0.5:.4f} skill units)")

# Quick sanity check
model.eval()
with torch.no_grad():
    # Test predictions at 3 skill targets
    test_skills = [0.1, 0.5, 0.9]
    print("\nSanity check (3 test inputs):")
    for target in test_skills:
        # Build a fake window of 3 levels at this skill
        fake_row = np.array([
            [5000 + (1 - target) * 15000, 10 + (1 - target) * 30, float(target > 0.3),
             int((1 - target) * 5), int((1 - target) * 1500), target]
        ] * 3, dtype=np.float32)  # (3, 6)
        # Normalise cols 0-4
        fake_row[:, :5] = (fake_row[:, :5] - mean) / std
        x = torch.tensor(fake_row, dtype=torch.float32).unsqueeze(0).to(DEVICE)
        pred = model(x).item()
        print(f"  Target skill {target:.1f}  →  Predicted {pred:.3f}")

print("\nDone. Update serve.py SessionState.estimate_skill() to use this model.")
